---
- name: Remote VM Part
  hosts: azure
  vars_files:
  - 'variables.yml'
  become_method: sudo
  become: true
  gather_facts: no
  tasks:

  - name: Wait for VM to become reachable
    wait_for_connection:

  - name: Modify default page
    copy:
      content: 'Ansible is awesome!'
      dest: '/var/www/html/index.nginx-debian.html'
    when: (nginx_default_msg is undefined) or (nginx_default_msg | length == 0)

  - name: Modify default page
    copy:
      content: "{{ nginx_default_msg }}"
      dest: '/var/www/html/index.nginx-debian.html'
    when: nginx_default_msg is defined

  - name: Restart nginx
    service:
      name: nginx
      state: restarted
#test pr