name: Build Docker Image

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'ansible/**'
      - 'azure/**'
      - 'docker/**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Start MailHog as a service
      mailhog:
        image: mailhog/mailhog:latest
        ports:
          - 1025:1025  # SMTP server port
          - 8025:8025  # Web UI port

    steps:
      # Checks out your repository
      - uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Docker login
        run: docker login -u ${{ secrets.DockerHubUser }} -p ${{ secrets.DockerHubToken }}

      # Install Python 3 and pip
      - name: Install Python 3 and pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 -m pip install --upgrade pip

      # Install required Python packages
      - name: Install Python packages
        run: |
          pip3 install ansible[azure] docker

      # Build and publish a custom Docker image
      - name: Docker build and push
        run: docker build -f ${GITHUB_WORKSPACE}/docker/Dockerfile -t ${{ secrets.DockerHubUser }}/${IMAGE_NAME}:latest . && docker push ${{ secrets.DockerHubUser }}/${IMAGE_NAME}:latest
        env:
          IMAGE_NAME: mysql  # Set IMAGE_NAME to the desired name

      # Pull and publish the official MySQL image
      - name: Pull MySQL image
        run: docker pull mysql:latest

      - name: Tag and push MySQL image
        run: docker tag mysql:latest ${{ secrets.DockerHubUser }}/mysql:latest && docker push ${{ secrets.DockerHubUser }}/mysql:latest

      # Optional: Test MailHog SMTP
      - name: Send test email to MailHog
        run: |
          echo "Testing MailHog by sending a sample email" | sendmail -S localhost:1025 test@example.com
